---

   - name: Create DHCP server Docker image from Dockerfile
     community.docker.docker_image:
       name: "{{ dhcp_docker_image_name }}"
       build:
         pull: yes
         path: "{{role_name}}/files/"
       state: present
       source: build

   - name: Deploy Docker container from Docker image
     community.docker.docker_container:
        name: "{{ dhcp_docker_container_name }}"
        image: "{{ dhcp_docker_image_name }}"
        state: started
        restart_policy: always
        networks:
          - name: "MACVLAN"
            ipv4_address: "{{ dhcp_docker_container_ip }}"
        volumes:
          - "./{{role_name}}/files/dhcpd.conf:/etc/dhcp/dhcpd.conf"
